# main = ".open-next/worker.js"
name = "skid-homework"
compatibility_date = "2025-12-13"
compatibility_flags = ["nodejs_compat"]
send_metrics = false

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
